public class AddressValidationQueueable implements Queueable {
    private Id accountId;
}

    // public AddressValidationQueueable(Id accId) {
    //     accountId = accId;
    // }

//     public void execute(QueueableContext context) {
//     //     // Account acc = [SELECT Id, Name, BillingStreet, BillingCity, BillingState, BillingPostalCode FROM Account WHERE Id = :accountId LIMIT 1];
//     //     acc.Validated__c = false;
//     //     HttpRequest request= new HttpRequest();
//     //     Http httpConnection = new Http();
//     //     HttpResponse response= new HttpResponse();
//     //     request.setEndpoint('');
//     //     request.setMethod('POST');
//     //     response = httpConnection.send(request);
//     //     if(response.getstatusCode()==200)
//     //     {

//     //     }

        
//     //     update acc;
//     // // }
// }



// // public class PersonnalInfoWrapper {
// //     public String name;
// //     public Integer age;
// //     public String email;
// // }

// // {
// //     "Name": "Raghul Prasath. S",
// //     "Age": 24,
// //     "Email": "Raghulsrinivasan1999@gmail.com"
// // }  
// }
